### ISSUE TITLE
[🐛] Snyk-monitor failing in AKS

### ISSUE THREAD

**Issue by pranaysahith** [snyk/kubernetes-monitor#1250]
- `kubernetes-monitor version - v1.100.0` 
- `Cloud runtime - AKS`

### Expected behaviour
snyk-monitor pod runs healthy

### Actual behaviour
snyk-monitor pod is in crashloop backoff state with errors in logs - 

```
{"name":"kubernetes-monitor","hostname":"snyk-monitor-68d88b84bc-bgffh","pid":7,"level":50,"code":"","error":{"message":"Too Many Requests","name":"Error","stack":"Error: Too Many Requests\n    at Request.<anonymous> (/srv/app/node_modules/@kubernetes/client-node/dist/watch.js:23:31)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at Request.onRequestResponse (/srv/app/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at HTTPParser.execute (<anonymous>)\n    at TLSSocket.socketOnData (node:_http_client:534:22)"},"msg":"unexpected informer error event occurred","time":"2023-02-02T10:46:41.738Z","v":0}
{"name":"kubernetes-monitor","hostname":"snyk-monitor-68d88b84bc-bgffh","pid":7,"level":50,"code":"","error":{"message":"Too Many Requests","name":"Error","stack":"Error: Too Many Requests\n    at Request.<anonymous> (/srv/app/node_modules/@kubernetes/client-node/dist/watch.js:23:31)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at Request.onRequestResponse (/srv/app/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at HTTPParser.execute (<anonymous>)\n    at TLSSocket.socketOnData (node:_http_client:534:22)"},"msg":"unexpected informer error event occurred","time":"2023-02-02T10:46:41.739Z","v":0}
{"name":"kubernetes-monitor","hostname":"snyk-monitor-68d88b84bc-bgffh","pid":7,"level":50,"code":"","error":{"message":"Too Many Requests","name":"Error","stack":"Error: Too Many Requests\n    at Request.<anonymous> (/srv/app/node_modules/@kubernetes/client-node/dist/watch.js:23:31)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at Request.onRequestResponse (/srv/app/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at HTTPParser.execute (<anonymous>)\n    at TLSSocket.socketOnData (node:_http_client:534:22)"},"msg":"unexpected informer error event occurred","time":"2023-02-02T10:46:41.741Z","v":0}
{"name":"kubernetes-monitor","hostname":"snyk-monitor-68d88b84bc-bgffh","pid":7,"level":50,"code":"","error":{"message":"HTTP request failed","name":"HttpError","stack":"HttpError: HTTP request failed\n    at Request._callback (/srv/app/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:14294:36)\n    at Request.self.callback (/srv/app/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at Request.<anonymous> (/srv/app/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at Request.emit (node:domain:489:12)\n    at IncomingMessage.<anonymous> (/srv/app/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)"},"msg":"error while listing namespace","time":"2023-02-02T10:46:41.748Z","v":0}
{"name":"kubernetes-monitor","hostname":"snyk-monitor-68d88b84bc-bgffh","pid":7,"level":50,"reason":{"response":{"statusCode":429,"body":"Too many requests, please try again later.\n","headers":{"audit-id":"9f82dcac-58f2-40e3-ba2e-83c891c07d68","cache-control":"no-cache, private","content-type":"text/plain; charset=utf-8","retry-after":"1","x-content-type-options":"nosniff","x-kubernetes-pf-flowschema-uid":"35b327af-8ef2-470d-a133-a232d9b0d219","x-kubernetes-pf-prioritylevel-uid":"86f513a7-ca6d-4052-85bc-3fbe698ccd2c","date":"Thu, 02 Feb 2023 10:46:41 GMT","content-length":"43","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"10.0.0.1:443","port":"443","hostname":"10.0.0.1","hash":null,"search":null,"query":null,"pathname":"/api/v1/namespaces/masked","path":"/api/v1/namespaces/masked","href":"https://10.0.0.1:443/api/v1/namespaces/masked"},"method":"GET","headers":{"Accept":"application/json","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlpTaDRPZ2h4eTN0ZEliTVM1VFFqSlE2OG44TnQ5RnZlMVJBaTJwRDh4NVUifQ.eyJhdWQiOlsiaHR0cHM6Ly93ZXUtY2RycGxhdGZvcm0tY2EzZjU1MzEuMmE4YmE2OTEtODNiMy00N2JjLWJkMDYtZmE2Y2M1NjQ5N2IzLnByaXZhdGVsaW5rLndlc3RldXJvcGUuYXptazhzLmlvIiwiXCJ3ZXUtY2RycGxhdGZvcm0tY2EzZjU1MzEuMmE4YmE2OTEtODNiMy00N2JjLWJkMDYtZmE2Y2M1NjQ5N2IzLnByaXZhdGVsaW5rLndlc3RldXJvcGUuYXptazhzLmlvXCIiLCJodHRwczovL3dldS1jZHJwbGF0Zm9ybS1jM2NjOWRkZC5oY3Aud2VzdGV1cm9wZS5hem1rOHMuaW8iLCJcIndldS1jZHJwbGF0Zm9ybS1jM2NjOWRkZC5oY3Aud2VzdGV1cm9wZS5hem1rOHMuaW9cIiJdLCJleHAiOjE3MDY4NzA3MzksImlhdCI6MTY3NTMzNDczOSwiaXNzIjoiaHR0cHM6Ly93ZXUtY2RycGxhdGZvcm0tY2EzZjU1MzEuMmE4YmE2OTEtODNiMy00N2JjLWJkMDYtZmE2Y2M1NjQ5N2IzLnByaXZhdGVsaW5rLndlc3RldXJvcGUuYXptazhzLmlvIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJjZHJwbGF0Zm9ybSIsInBvZCI6eyJuYW1lIjoic255ay1tb25pdG9yLTY4ZDg4Yjg0YmMtYmdmZmgiLCJ1aWQiOiI3Yzc1NjEyYy03ZDYwLTQ3MjItOWE1OC1kN2MxZjBiNDJkMDIifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6InNueWstbW9uaXRvciIsInVpZCI6IjBkZTA5ODM4LWZiMWEtNDkwZS04MzNiLTVjMTdjN2EzNTY5YSJ9LCJ3YXJuYWZ0ZXIiOjE2NzUzMzgzNDZ9LCJuYmYiOjE2NzUzMzQ3MzksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjZHJwbGF0Zm9ybTpzbnlrLW1vbml0b3IifQ.NFsE8kRRHuKqDgAzB_yX-fVUjbuPugpaXLWoRkPsCqjeJbHn9vA4if7P9SpFGEF-KlPFHE21n6TwfzWKifsT-u3KMNn4QNMok66HdNbpMBUWbi5Sr6RiziDSRNC1xZ2qJMLyNsAQKG6FbdXG3NJ5LUvW9s_HGIeoLLLlT3ui9icpTDG6nMdJtd_ny93yswiQgjxUshQBjNf1ysD8MEY997sZYKaE4Q0ljoQunW4hfcWDkeD8Ba5i9BTSggz0wyabqsNpTv4HB-eS3eWxwbhuhoz4qRSLdmXy0-IRkaYdPT_iMyfCdHM1S5ZNiJfnWw2eGo8S2WgdrLxbBzNO-OvlJ93rrPGzIk9tbloOgdBz2lsm-NZOc-21JXsEOKGpnv48C6mFPVKs2r9PNzU11T1HiTM1yBWYMsm4JF13xOs30vZC4ksFV4SjaZTfnJna2TqUu11M5HsRiRg0CZhFYQ1OTZficp09bmt4Oqs9rpEWziiZRpCLKWDAmtx9joF94IASenGMRuKZt73pdgnEM8ejYhVh4StPkiG34HzjiIR2cMEqTEu1eantyDuzCFwDyvYhLnV-N0hJSY9iL5xxsW-yNiAR1Bd_vyAGEUjec740RDFT58Bk7rZPAaFfEccKQKIF03gnl9nVqYSLQpGp8lySVUeDQ0OGa-_9bNWAAI9Egug"}}},"body":"Too many requests, please try again later.\n","statusCode":429,"name":"HttpError"},"promise":{},"msg":"UNHANDLED REJECTION!","time":"2023-02-02T10:46:41.749Z","v":0}
```

### Steps to reproduce
Install helm chart - 
```
helm upgrade --install snyk-monitor snyk-charts/snyk-monitor \
  --version 1.100.0 \
  --set clusterName="${snykClusterName}" \
  --set scope=Namespaced \
  --set policyOrgs="${snykOrgId}"
```

### Screenshots
![image](https://user-images.githubusercontent.com/2724669/216305164-1605d7cc-0d45-491e-8e80-e79290f5a86b.png)

**Comment by ivanstanev** [comment]
Hey @pranaysahith, thank you for raising this. We have just released version 1.102.1, which should address the issue.
Could you please upgrade and let us know if it resolved the problem for you?
